---
- hosts: all
  vars: 
    py3env: /vagrant/py3env
    dbname: aurora
    dbuser: aurora_dbuser
    dbpassword: nosecret
  tasks:
#  - name: apt-get update
#    apt: update_cache=yes
#    become: yes
  - command: locale-gen en_US.UTF-8
  - command: update-locale LANG=en_US.UTF-8
  - apt: pkg=vim
  - apt: pkg=libjpeg-dev

  - apt: pkg=postgresql
  - apt: pkg=python-psycopg2
#  - apt: pkg=postgresql-server-dev-9.5
  - apt: pkg=libpq-dev
  - apt: pkg=python3-dev

  - name: throw away postgres cluster
    command: pg_dropcluster --stop 9.5 main
    become: yes
    become_user: postgres

  - name: create new postgres cluster with UTF-8 encoding
    command: pg_createcluster --locale=en_US.UTF-8 --start 9.5 main
    become: yes
    become_user: postgres

  - postgresql_user: name={{ dbuser }}
                     password={{ dbpassword }}
    become: yes
    become_user: postgres

  - name: create database {{ dbname }}
    postgresql_db: name={{ dbname }}
                   owner={{ dbuser }}
                   encoding='UTF-8'
                   lc_collate='en_US.UTF-8'
                   lc_ctype='en_US.UTF-8'
    become: yes
    become_user: postgres

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
    become: yes
    become_user: postgres

  - apt: pkg=python-pip
  - apt: pkg=python3
  - apt: pkg=python3-dev
  - pip: name=virtualenv
  - name: create virtualenv
    command: virtualenv {{ py3env }} -p python3
             creates={{ py3env }}
    become: yes
#    become_user: ubuntu

# ipython not working with python manage.py shell anymore :(
  - name: install ipython into virtualenv
    pip: name=ipython
         virtualenv={{ py3env }}
    become: yes
#    become_user: ubuntu
  - name: install psycopg2 into virtualenv
    pip: name=psycopg2
         virtualenv={{ py3env }}
    become: yes
#    become_user: ubuntu
  - name: install invoke into virtualenv
    pip: name=invoke
         virtualenv={{ py3env }}
    become: yes
#    become_user: ubuntu
  - name: install project requirements
    pip: requirements=/vagrant/requirements_dev.txt
         virtualenv={{ py3env }}
    become: yes
#    become_user: ubuntu

#  - name: build sherlock
#    shell: python3 setup.py sdist
#    args:
#      chdir: /vagrant/PlagCheck/hashing/sherlock
#    become: yes
#    become_user: ubuntu

#  - name: install sherlock into virtualenv
#    pip: name=/vagrant/PlagCheck/hashing/sherlock/dist/sherlock-1.0.tar.gz
#         virtualenv={{ py3env }}
#    become: yes
#    become_user: ubuntu

  - name: add automatic activation of virtualenv to .bashrc
    lineinfile: dest=/home/ubuntu/.bashrc
                line=". {{ py3env }}/bin/activate"
    become: yes
#    become_user: ubuntu
  - lineinfile: dest=/home/ubuntu/.bashrc
                line='cd /vagrant'
    become: yes
#    become_user: ubuntu
  - lineinfile: dest=/home/ubuntu/.bashrc
                line='export LANGUAGE=en_US.UTF-8'
    become: yes
#    become_user: ubuntu
  - lineinfile: dest=/home/ubuntu/.bashrc
                line='export LANG=en_US.UTF-8'
    become: yes
#    become_user: ubuntu
  - lineinfile: dest=/home/ubuntu/.bashrc
                line='export LC_ALL=en_US.UTF-8'
    become: yes
#    become_user: ubuntu
